ame: Semgrep
on: [push, pull_request]
jobs:
    semgrep:
        runs-on: ubuntu-latest
        name: Check
        steps:
            - uses: actions/checkout@v1
            - uses: returntocorp/semgrep-action@v1
              with:
                config: p/r2c
